# x=5
# y="hello"
# z=x+y

# try catch block to resolve it

x=5
y="hello"
try:
    z=x+y
except TypeError:
    print("error")